<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmailTemplateSeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        $templates = [
            [
                "name"                => "Welcome Email",
                "slug"                => "WELCOME_EMAIL",
                "subject"             => "Welcome to Credit Lite",
                "email_body"          => "<div class='content'> <h1>Welcome to Credit Lite, {{customerName}}!</h1> <p>We're thrilled to have you onboard. 🚀</p> <p>Credit Lite is your all-in-one HRM & Payroll system designed to streamline your business operations. With our powerful tools, you can manage:</p> <ul style='text-align: left; padding: 0 40px;'> <li><b>HR & Employee Management</b> – Track employee records & attendance.</li> <li><b>Payroll Processing</b> – Automate salary & tax calculations.</li> <li><b>Employee Self-Service Portal</b> – Access payslips, leave requests & more.</li> <li><b>Accounting & Finance</b> – Manage expenses, invoices & reports.</li> <li><b>Loan Management</b> – Handle employee loans with ease.</li> <li><b>Task & Project Management</b> – Assign, track, and collaborate.</li> </ul> <a href='{{loginLink}}' class='btn'>Login to Credit Lite</a> <p>Need help? Send us email at <a href='mailto:info@creditlite.com'>info@creditlite.com</a>.</p> <p>Let’s build a smarter workplace together!</p> </div>",
                "sms_body"            => "",
                "notification_body"   => "",
                "shortcode"           => "{{customerName}} {{loginLink}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 1,
                "template_type"       => 'admin',
            ],
            [
                "name"                => "Trial Period Ended",
                "slug"                => "TRIAL_PERIOD_ENDED",
                "subject"             => "Credit Lite Trial Ended",
                "email_body"          => "<div style='font-family: Arial, sans-serif; font-size: 14px;'> <h2 style='color: #333333;'>Credit Lite Trial Ended</h2> <p>Dear {{customerName}},</p> <p>We hope this email finds you well. We wanted to remind you that your trial period has ended as of {{trialEndDate}}.</p> <p>We hope you found our service useful during the trial period. If you would like to continue using our service, please pay for subscription.</p> <p>If you have any questions or concerns, please do not hesitate to contact us. We are always here to help.</p> <p>Thank you for your interest in our service. We hope to continue serving you in the future.</p> </div>",
                "sms_body"            => "",
                "notification_body"   => "",
                "shortcode"           => "{{customerName}} {{trialEndDate}} {{planName}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 1,
                "template_type"       => 'admin',
            ],
            [
                "name"                => "Subscription Reminder",
                "slug"                => "SUBSCRIPTION_REMINDER",
                "subject"             => "Subscription Reminder",
                "email_body"          => "<div style='font-family: Arial, sans-serif; font-size: 14px;'> <h2 style='color: #333333;'>Credit Lite Renewal Reminder </h2> <p>Dear {{customerName}},</p> <p>We hope this email finds you well. We wanted to remind you that your subscription is expiring on {{expiryDate}}.</p> <p>If you want to continue using our service, please renew your subscription by visiting our website and selecting a subscription plan that suits your needs.</p> <p>If you have already renewed your subscription, please disregard this email. Otherwise, please renew your subscription before the expiry date to avoid any interruption in your service.</p> <p>If you have any questions or concerns, please do not hesitate to contact us. We are always here to help.</p> <p>Thank you for choosing our service. We appreciate your business and look forward to continuing to serve you.</p> </div>",
                "sms_body"            => "",
                "notification_body"   => "",
                "shortcode"           => "{{customerName}} {{expiryDate}} {{planName}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 1,
                "template_type"       => 'admin',
            ],
            [
                "name"                => "Subscription Payment Confirmation",
                "slug"                => "SUBSCRIPTION_PAYMENT_CONFIRMATION",
                "subject"             => "Subscription Payment Confirmation",
                "email_body"          => "<div style='font-family: Arial, sans-serif; font-size: 14px;'> <h2 style='color: #333333;'>Credit Lite Payment Confirmation</h2> <p>Dear {{customerName}},</p> <p>Thank you for renewing your subscription to (Package Name: {{packageName}}). Your payment has been received and your subscription has been renewed until {{expiryDate}}.</p> <p>You can now continue using our service without any interruption. If you have any questions or concerns, please do not hesitate to contact us. We are always here to help.</p> <p>Thank you for choosing our service. We appreciate your business and look forward to continuing to serve you.</p> </div>",
                "sms_body"            => "",
                "notification_body"   => "",
                "shortcode"           => "{{customerName}} {{expiryDate}} {{planName}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 1,
                "template_type"       => 'admin',
            ],
            [
                "name"                => "New Message",
                "slug"                => "NEW_MESSAGE",
                "subject"             => "You Have a New Message",
                "email_body"          => "<div style='font-family: Arial, sans-serif; font-size: 14px;'><p>Hi {{recipientName}},</p> <p>I hope this email finds you well.</p> <p>This is to inform you that you have received a new message. <p>Please login to your account to view the full message.</p></div>",
                "sms_body"            => "You have received a new message. Please login to your account to see the message.",
                "notification_body"   => "<p>Hi {{recipientName}},</p><p>You have received a new message.</p><p><a class='btn btn-primary btn-xs mt-2' href='{{messageLink}}'>View Message</a></p>",
                "shortcode"           => "{{recipientName}} {{loginUrl}} {{messageLink}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "Transfer Money",
                "slug"                => "TRANSFER_MONEY",
                "subject"             => "Transfer Money",
                "email_body"          => "<div>\r\n<div>Dear {{name}},</div>\r\n<div>You have received {{amount}} to {{account_number}} from {{sender_account_number}} on {{dateTime}}</div>\r\n</div>",
                "sms_body"            => "Dear {{name}}, You have received {{amount}} to {{account_number}} from {{sender_account_number}} on {{dateTime}}",
                "notification_body"   => "Dear {{name}}, You have received {{amount}} to {{account_number}} from {{sender_account_number}} on {{dateTime}}",
                "shortcode"           => "{{name}} {{account_number}} {{amount}} {{sender}} {{sender_account_number}} {{balance}} {{dateTime}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "Deposit Money",
                "slug"                => "DEPOSIT_MONEY",
                "subject"             => "Deposit Money",
                "email_body"          => "<div>\r\n<div>Dear {{name}},</div>\r\n<div>Your account has been credited with {{amount}} on {{dateTime}}</div>\r\n</div>",
                "sms_body"            => "Dear {{name}}, Your account has been credited with {{amount}} on {{dateTime}}",
                "notification_body"   => "Dear {{name}}, Your account has been credited with {{amount}} on {{dateTime}}",
                "shortcode"           => "{{name}} {{account_number}} {{amount}} {{dateTime}} {{balance}} {{depositMethod}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "Deposit Request Approved",
                "slug"                => "DEPOSIT_REQUEST_APPROVED",
                "subject"             => "Deposit Request Approved",
                "email_body"          => "<div>\r\n<div>Dear {{name}},</div>\r\n<div>Your deposit request has been approved. Your account {{account_number}} has been credited with {{amount}} on {{dateTime}}</div>\r\n</div>",
                "sms_body"            => "Dear {{name}}, Your deposit request has been approved. Your account {{account_number}} has been credited with {{amount}} on {{dateTime}}",
                "notification_body"   => "Dear {{name}}, Your deposit request has been approved. Your account {{account_number}} has been credited with {{amount}} on {{dateTime}}",
                "shortcode"           => "{{name}} {{account_number}} {{amount}} {{dateTime}} {{balance}} {{depositMethod}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "Loan Request Approved",
                "slug"                => "LOAN_REQUEST_APPROVED",
                "subject"             => "Loan Request Approved",
                "email_body"          => "<div>\r\n<div>Dear {{name}},</div>\r\n<div>Your loan request of {{amount}} has been approved on {{dateTime}}</div>\r\n</div>",
                "sms_body"            => "Dear {{name}}, Your loan request of {{amount}} has been approved on {{dateTime}}",
                "notification_body"   => "Dear {{name}}, Your loan request of {{amount}} has been approved on {{dateTime}}",
                "shortcode"           => "{{name}} {{amount}} {{dateTime}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "Withdraw Request Approved",
                "slug"                => "WITHDRAW_REQUEST_APPROVED",
                "subject"             => "Withdraw Request Approved",
                "email_body"          => "<div>\r\n<div>Dear {{name}},</div>\r\n<div>Your withdraw request has been approved. Your account has been debited with {{amount}} on {{dateTime}}</div>\r\n</div>",
                "sms_body"            => "Dear {{name}}, Your withdraw request has been approved. Your account has been debited with {{amount}} on {{dateTime}}",
                "notification_body"   => "Dear {{name}}, Your withdraw request has been approved. Your account has been debited with {{amount}} on {{dateTime}}",
                "shortcode"           => "{{name}} {{account_number}} {{amount}} {{withdrawMethod}} {{balance}} {{dateTime}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "Deposit Request Rejected",
                "slug"                => "DEPOSIT_REQUEST_REJECTED",
                "subject"             => "Deposit Request Rejected",
                "email_body"          => "<div>\r\n<div>Dear {{name}},</div>\r\n<div>Your deposit request of {{amount}} has been rejected.</div>\r\n<div>&nbsp;</div>\r\n<div>Amount:&nbsp;{{amount}}</div>\r\n<div>Deposit Method: {{depositMethod}}</div>\r\n</div>",
                "sms_body"            => "Dear {{name}}, Your deposit request of {{amount}} has been rejected.",
                "notification_body"   => "Dear {{name}}, Your deposit request of {{amount}} has been rejected.",
                "shortcode"           => "{{name}}  {{account_number}} {{amount}} {{depositMethod}} {{balance}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "Loan Request Rejected",
                "slug"                => "LOAN_REQUEST_REJECTED",
                "subject"             => "Loan Request Rejected",
                "email_body"          => "<div>\r\n<div>Dear {{name}},</div>\r\n<div>Your loan request of {{amount}} has been rejected on {{dateTime}}</div>\r\n</div>",
                "sms_body"            => "Dear {{name}}, Your loan request of {{amount}} has been rejected on {{dateTime}}",
                "notification_body"   => "Dear {{name}}, Your loan request of {{amount}} has been rejected on {{dateTime}}",
                "shortcode"           => "{{name}} {{amount}} {{dateTime}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "Withdraw Request Rejected",
                "slug"                => "WITHDRAW_REQUEST_REJECTED",
                "subject"             => "Withdraw Request Rejected",
                "email_body"          => "<div>\r\n<div>Dear {{name}}, Your withdraw request has been rejected. Your transferred amount {{amount}} has returned back to your account.</div>\r\n</div>",
                "sms_body"            => "Dear {{name}}, Your withdraw request has been rejected. Your transferred amount {{amount}} has returned back to your account.",
                "notification_body"   => "Dear {{name}}, Your withdraw request has been rejected. Your transferred amount {{amount}} has returned back to your account.",
                "shortcode"           => "{{name}} {{account_number}} {{amount}} {{withdrawMethod}} {{dateTime}} {{balance}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "Withdraw Money",
                "slug"                => "WITHDRAW_MONEY",
                "subject"             => "Withdraw Money",
                "email_body"          => "<div>\r\n<div>Dear {{name}},</div>\r\n<div>Your account has been debited with {{amount}} on {{dateTime}}</div>\r\n</div>",
                "sms_body"            => "Dear {{name}}, Your account has been debited with {{amount}} on {{dateTime}}",
                "notification_body"   => "Dear {{name}}, Your account has been debited with {{amount}} on {{dateTime}}",
                "shortcode"           => "{{name}} {{account_number}} {{amount}} {{dateTime}} {{withdrawMethod}} {{balance}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "Member Request Accepted",
                "slug"                => "MEMBER_REQUEST_ACCEPTED",
                "subject"             => "Member Request Accepted",
                "email_body"          => "<div>\r\n<div>Dear {{name}},</div>\r\n<div>Your member request has been accepted by authority on {{dateTime}}. You can now login to your account by using your email and password.</div>\r\n</div>",
                "sms_body"            => "",
                "notification_body"   => "",
                "shortcode"           => "{{name}} {{member_no}} {{dateTime}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 1,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "Loan Payment Received",
                "slug"                => "LOAN_PAYMENT_RECEIVED",
                "subject"             => "Loan Payment Received Confirmation",
                "email_body"          => "<p>Dear <strong>{{name}}</strong>,</p> <p>We have successfully received your loan payment of <strong>{{amount}}</strong> on <strong>{{dateTime}}</strong>. Thank you for your payment.</p> <p><strong>Payment Details:</strong></p> <ul> <li><strong>Loan ID:</strong> {{loanID}}</li> <li><strong>Payment Amount:</strong> {{amount}}</li> <li><strong>Payment Date:</strong> {{dateTime}}</li> <li><strong>Next Due Date:</strong> {{nextDueDate}}</li></ul>",
                "sms_body"            => "Dear {{name}}, We have successfully received your loan payment of {{amount}} on {{dateTime}}. Thank you for your payment.",
                "notification_body"   => "Dear {{name}}, We have successfully received your loan payment of {{amount}} on {{dateTime}}. Thank you for your payment.",
                "shortcode"           => "{{name}} {{amount}} {{loanID}} {{nextDueDate}} {{dateTime}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "Overdue Loan Payment",
                "slug"                => "OVERDUE_LOAN_PAYMENT",
                "subject"             => "Overdue Loan Payment Alert",
                "email_body"          => "<p>Dear <strong>{{name}}</strong>,</p> <p>We regret to inform you that your loan account has entered default status due to non-payment. Your loan payment of <strong>{{dueAmount}}</strong> was due on <strong>{{dueDate}}</strong>, and despite our previous reminders, we have not received the payment. Immediate action is required to prevent further consequences, including additional fees or legal actions.</p> <p><strong>Loan Details:</strong></p> <ul> <li><strong>Loan ID:</strong> {{loanID}}</li> <li><strong>Default Amount:</strong> {{dueAmount}}</li> <li><strong>Number of Due:</strong> {{numberOfDue}}</li> <li><strong>Due Date:</strong> {{dueDate}}</li> </ul> <p>We urge you to make the payment immediately or contact us to discuss your options. Failure to resolve this matter may result in additional penalties or legal actions.</p>",
                "sms_body"            => "Dear {{name}}, your loan account has entered default due to non-payment of {{dueAmount}}. Please make the payment immediately to avoid further consequences. Loan ID: {{loanID}}. Due Date: {{dueDate}}.",
                "notification_body"   => "Dear {{name}}, your loan account has entered default due to non-payment of {{dueAmount}}. Please make the payment immediately to avoid further consequences. Loan ID: {{loanID}}. Due Date: {{dueDate}}.",
                "shortcode"           => "{{name}} {{dueAmount}} {{numberOfDue}} {{loanID}} {{dueDate}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "Upcoming Loan Payment Reminder",
                "slug"                => "UPCOMING_LOAN_PAYMENT_REMINDER",
                "subject"             => "Upcoming Loan Payment Reminder",
                "email_body"          => "<p>Dear <strong>{{name}}</strong>,</p> <p>This is a friendly reminder that your next loan payment of <strong>{{amount}}</strong> for Loan ID <strong>{{loanID}}</strong> is due on <strong>{{dueDate}}</strong>. Please ensure timely payment to avoid any penalties.</p> <p><strong>Payment Details:</strong></p> <ul> <li><strong>Loan ID:</strong> {{loanID}}</li> <li><strong>Payment Amount:</strong> {{amount}}</li> <li><strong>Due Date:</strong> {{dueDate}}</li></ul> <p>If you have any questions, feel free to contact us at <a href='mailto:support@company.com'>support@company.com</a>.</p>",
                "sms_body"            => "Dear {{name}}, your next loan payment of {{amount}} for Loan ID {{loanID}} is due on {{dueDate}}. Please make the payment on time to avoid penalties.",
                "notification_body"   => "Dear {{name}}, your next loan payment of {{amount}} for Loan ID {{loanID}} is due on {{dueDate}}. Please make the payment on time to avoid penalties.",
                "shortcode"           => "{{name}} {{amount}} {{loanID}} {{dueDate}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "E-Signature Document Sent",
                "slug"                => "ESIGNATURE_DOCUMENT_SENT",
                "subject"             => "Document Sent for Signature - {{documentTitle}}",
                "email_body"          => "<div style='font-family: Arial, sans-serif; font-size: 14px;'><p>Hi {{signerName}},</p><p>You have received a document that requires your digital signature.</p><p><strong>Document Details:</strong></p><ul><li><strong>Title:</strong> {{documentTitle}}</li><li><strong>Type:</strong> {{documentType}}</li><li><strong>From:</strong> {{senderName}} {{senderCompany}}</li><li><strong>Expires:</strong> {{expiresAt}}</li></ul>{{#customMessage}}<p><strong>Message from sender:</strong></p><p>{{customMessage}}</p>{{/customMessage}}<p>Please click the link below to review and sign the document:</p><a href='{{signingUrl}}' style='background-color: #007bff; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block;'>Sign Document</a><p>If you have any questions, please contact {{senderName}} at {{senderCompany}}.</p><p>Thank you!</p></div>",
                "sms_body"            => "Document '{{documentTitle}}' requires your signature from {{senderName}}. Sign at: {{signingUrl}} (Expires: {{expiresAt}})",
                "notification_body"   => "<p>New document requires your signature: <strong>{{documentTitle}}</strong></p><p>From: {{senderName}} {{senderCompany}}</p><p>Expires: {{expiresAt}}</p><p><a class='btn btn-primary btn-xs mt-2' href='{{signingUrl}}'>Sign Document</a></p>",
                "shortcode"           => "{{signerName}} {{signerEmail}} {{documentTitle}} {{documentType}} {{senderName}} {{senderCompany}} {{customMessage}} {{signingUrl}} {{expiresAt}} {{loginUrl}}",
                "email_status"        => 1,
                "sms_status"          => 1,
                "notification_status" => 1,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "E-Signature Document Signed",
                "slug"                => "ESIGNATURE_DOCUMENT_SIGNED",
                "subject"             => "Document Signed - {{documentTitle}}",
                "email_body"          => "<div style='font-family: Arial, sans-serif; font-size: 14px;'><p>Hi {{senderName}},</p><p>Great news! {{signerName}} has successfully signed your document.</p><p><strong>Document Details:</strong></p><ul><li><strong>Title:</strong> {{documentTitle}}</li><li><strong>Type:</strong> {{documentType}}</li><li><strong>Signer:</strong> {{signerName}} ({{signerEmail}})</li><li><strong>Signed At:</strong> {{signedAt}}</li></ul><p>You can view the document or download a signed copy using the links below:</p><a href='{{documentUrl}}' style='background-color: #28a745; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block; margin-right: 10px;'>View Document</a><a href='{{downloadUrl}}' style='background-color: #007bff; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block;'>Download Document</a><p>Thank you for using our e-signature service!</p></div>",
                "sms_body"            => "Document '{{documentTitle}}' has been signed by {{signerName}} at {{signedAt}}. View: {{documentUrl}}",
                "notification_body"   => "<p>Document signed: <strong>{{documentTitle}}</strong></p><p>Signer: {{signerName}} ({{signerEmail}})</p><p>Signed: {{signedAt}}</p><p><a class='btn btn-success btn-xs mt-2' href='{{documentUrl}}'>View Document</a></p>",
                "shortcode"           => "{{signerName}} {{signerEmail}} {{documentTitle}} {{documentType}} {{senderName}} {{senderCompany}} {{signedAt}} {{documentUrl}} {{downloadUrl}} {{loginUrl}}",
                "email_status"        => 1,
                "sms_status"          => 1,
                "notification_status" => 1,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "E-Signature Document Completed",
                "slug"                => "ESIGNATURE_DOCUMENT_COMPLETED",
                "subject"             => "Document Fully Signed - {{documentTitle}}",
                "email_body"          => "<div style='font-family: Arial, sans-serif; font-size: 14px;'><p>Hi {{senderName}},</p><p>Excellent news! Your document has been fully signed by all required parties.</p><p><strong>Document Details:</strong></p><ul><li><strong>Title:</strong> {{documentTitle}}</li><li><strong>Type:</strong> {{documentType}}</li><li><strong>Total Signers:</strong> {{signerCount}}</li><li><strong>Completed At:</strong> {{completedAt}}</li></ul><p>All signatures have been collected and the document is now complete. You can download the final signed document using the link below:</p><a href='{{downloadUrl}}' style='background-color: #28a745; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block;'>Download Signed Document</a><p>The signed document is now legally binding and ready for your records.</p><p>Thank you for using our e-signature service!</p></div>",
                "sms_body"            => "Document '{{documentTitle}}' is now fully signed by all {{signerCount}} parties. Download: {{downloadUrl}}",
                "notification_body"   => "<p>Document fully signed: <strong>{{documentTitle}}</strong></p><p>All {{signerCount}} signatures collected</p><p>Completed: {{completedAt}}</p><p><a class='btn btn-success btn-xs mt-2' href='{{downloadUrl}}'>Download Signed Document</a></p>",
                "shortcode"           => "{{documentTitle}} {{documentType}} {{senderName}} {{senderCompany}} {{completedAt}} {{signerCount}} {{documentUrl}} {{downloadUrl}} {{loginUrl}}",
                "email_status"        => 1,
                "sms_status"          => 1,
                "notification_status" => 1,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "E-Signature Document Expired",
                "slug"                => "ESIGNATURE_DOCUMENT_EXPIRED",
                "subject"             => "Document Expired - {{documentTitle}}",
                "email_body"          => "<div style='font-family: Arial, sans-serif; font-size: 14px;'><p>Hi {{senderName}},</p><p>This is to inform you that your document has expired and is no longer available for signing.</p><p><strong>Document Details:</strong></p><ul><li><strong>Title:</strong> {{documentTitle}}</li><li><strong>Type:</strong> {{documentType}}</li><li><strong>Expired At:</strong> {{expiredAt}}</li><li><strong>Pending Signers:</strong> {{pendingSigners}}</li></ul><p>The document expired before all required signatures were collected. If you need to continue with the signing process, please create a new document and resend it to the signers.</p><p><a href='{{documentUrl}}' style='background-color: #007bff; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block;'>View Document Details</a></p><p>If you have any questions, please contact support.</p></div>",
                "sms_body"            => "Document '{{documentTitle}}' has expired with {{pendingSigners}} pending signatures. Expired: {{expiredAt}}",
                "notification_body"   => "<p>Document expired: <strong>{{documentTitle}}</strong></p><p>Expired: {{expiredAt}}</p><p>Pending signers: {{pendingSigners}}</p><p><a class='btn btn-warning btn-xs mt-2' href='{{documentUrl}}'>View Details</a></p>",
                "shortcode"           => "{{documentTitle}} {{documentType}} {{senderName}} {{senderCompany}} {{expiredAt}} {{pendingSigners}} {{documentUrl}} {{loginUrl}}",
                "email_status"        => 1,
                "sms_status"          => 1,
                "notification_status" => 1,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "E-Signature Document Cancelled",
                "slug"                => "ESIGNATURE_DOCUMENT_CANCELLED",
                "subject"             => "Document Cancelled - {{documentTitle}}",
                "email_body"          => "<div style='font-family: Arial, sans-serif; font-size: 14px;'><p>Hi,</p><p>This is to inform you that the document signing process has been cancelled.</p><p><strong>Document Details:</strong></p><ul><li><strong>Title:</strong> {{documentTitle}}</li><li><strong>Type:</strong> {{documentType}}</li><li><strong>From:</strong> {{senderName}} {{senderCompany}}</li><li><strong>Cancelled At:</strong> {{cancelledAt}}</li></ul><p>The document is no longer available for signing. If you believe this was done in error, please contact {{senderName}} for clarification.</p><p><a href='{{documentUrl}}' style='background-color: #6c757d; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block;'>View Document Details</a></p><p>Thank you for your understanding.</p></div>",
                "sms_body"            => "Document '{{documentTitle}}' from {{senderName}} has been cancelled. Cancelled: {{cancelledAt}}",
                "notification_body"   => "<p>Document cancelled: <strong>{{documentTitle}}</strong></p><p>From: {{senderName}} {{senderCompany}}</p><p>Cancelled: {{cancelledAt}}</p><p><a class='btn btn-secondary btn-xs mt-2' href='{{documentUrl}}'>View Details</a></p>",
                "shortcode"           => "{{documentTitle}} {{documentType}} {{senderName}} {{senderCompany}} {{cancelledAt}} {{documentUrl}} {{loginUrl}}",
                "email_status"        => 1,
                "sms_status"          => 1,
                "notification_status" => 1,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
            [
                "name"                => "E-Signature Reminder",
                "slug"                => "ESIGNATURE_REMINDER",
                "subject"             => "Reminder: Please Sign Document - {{documentTitle}}",
                "email_body"          => "<div style='font-family: Arial, sans-serif; font-size: 14px;'><p>Hi {{signerName}},</p><p>This is a friendly reminder that you have a document waiting for your signature.</p><p><strong>Document Details:</strong></p><ul><li><strong>Title:</strong> {{documentTitle}}</li><li><strong>Type:</strong> {{documentType}}</li><li><strong>From:</strong> {{senderName}} {{senderCompany}}</li><li><strong>Expires:</strong> {{expiresAt}} ({{daysRemaining}} days remaining)</li></ul><p>Please sign the document as soon as possible to avoid any delays. Click the link below to review and sign:</p><a href='{{signingUrl}}' style='background-color: #007bff; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block;'>Sign Document Now</a><p>If you have already signed this document, please disregard this reminder.</p><p>Thank you for your prompt attention to this matter!</p></div>",
                "sms_body"            => "Reminder: Document '{{documentTitle}}' from {{senderName}} needs your signature. {{daysRemaining}} days left. Sign: {{signingUrl}}",
                "notification_body"   => "<p>Reminder: Document needs signing</p><p><strong>{{documentTitle}}</strong></p><p>From: {{senderName}} {{senderCompany}}</p><p>Expires: {{expiresAt}} ({{daysRemaining}} days left)</p><p><a class='btn btn-warning btn-xs mt-2' href='{{signingUrl}}'>Sign Now</a></p>",
                "shortcode"           => "{{signerName}} {{signerEmail}} {{documentTitle}} {{documentType}} {{senderName}} {{senderCompany}} {{signingUrl}} {{expiresAt}} {{daysRemaining}} {{loginUrl}}",
                "email_status"        => 1,
                "sms_status"          => 1,
                "notification_status" => 1,
                "template_mode"       => 0,
                "template_type"       => 'tenant',
            ],
        ];

        foreach ($templates as $template) {
            $existingTemplate = DB::table('email_templates')
                ->where('slug', $template['slug'])
                ->first();

            if ($existingTemplate) {
                DB::table('email_templates')
                    ->where('slug', $template['slug'])
                    ->update(['shortcode' => $template['shortcode']]);
            } else {
                DB::table('email_templates')->insert($template);
            }
        }
    }
}
